name: random_number_generator
description: A simple app to generate random numbers


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

#launcher icons
# after config runs 'flutter pub get' and 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/icon/icon_ios.png
  image_path_android: assets/icon/icon_android.png
  adaptive_icon_background: assets/icon/icon_background.png
  adaptive_icon_foreground: assets/icon/icon_foreground.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
